### ISSUE TITLE
Stats for Boss Fights

### ISSUE THREAD

**Issue by jahink17** [CSC207-2022F-UofT/course-project-studyhero#30]
@AVLTG Does the boss's HP get reset every fight? Like if I reduce the boss's HP to 50% in one fight and then the fight ends (say because I lost all my HP), in the next fight will the boss's fight be restored to 100% or no?

I ask because, if it does get restored, maybe it's best to have the boss's hp as an instance variable in the BossFight class (or however you're implementing boss fights -- some clarification required here perhaps) rather than as an instance variable in the Stats class...since there's no point in having Stats store the boss's hp and then change it after every fight to restore it. It could also possibly violate SRP since both you (who's working on the boss fights) and I (who's working on the user's stats) might have to access and change stuff about how the boss's stats are implemented.

Let me know what you think.

**Comment by AVLTG** [comment]
@jahink17 Yes I believe the boss's HP does get reset every fight, however, I won't be accessing the boss's HP very often so I don't see a reason as to have it in the BossFight class. I don't know about implementation, as I think it would make sense that you have the boss HP and damage stats yourself, since you also need to make sure to scale the boss at every increasing level. I only need to access whether the boss is at 0 HP or not, and what the boss's damage is (I only need to access this once at the start of combat, and only if the player selects a consumable which is done by @m1k2l3 not by me, and that again relates to you and changing the player stats)

**Comment by jahink17** [comment]
Yeah that makes sense, thanks. After our conversation today here's what I've decided: [new issue about implementation](https://github.com/CSC207-2022F-UofT/course-project-studyhero/issues/41)
