### ISSUE TITLE
Unable to merge branches locally

### ISSUE THREAD

**Issue by jfongli** [CSC207-2022F-UofT/course-project-studyhero#39]
Every time I try to merge a branch, an error along the lines of "Could not merge [branch], the following untracked working tree files would be overwritten by merge: [...] Please move or remove them before you merge. Aborting." 
If anyone has a solution to this, let me know!

**Comment by AVLTG** [comment]
The main issue with trying to merge would be if the Gradle is also trying to get changed. I'm not sure why this issue really happens, however, if IntelliJ brings a popup of things to overwrite, make sure you check off the Gradle files and directories so that they are *NOT* going to overwrite. It should be good

**Comment by jfongli** [comment]
@AVLTG Thanks! I managed to merge most of the branches. However, for a couple of branches branches, such as 10-boss-fight, I get a message that says 
"The following untracked working tree files would be overwritten by merge: .DS_Store Please move or remove them before you merge. Aborting"
Any idea of how to solve this one?

**Comment by jfongli** [comment]
Update?: I've decided to just delete my local copy and clone a new one, so I'm closing this issue.
