### ISSUE TITLE
Stats needed for boss fights

### ISSUE THREAD

**Issue by jahink17** [CSC207-2022F-UofT/course-project-studyhero#41]
This issue is mostly for my own reference, to keep track of any thoughts/fixes. However, feel free to comment.

For now, we're implementing a separate Boss stats class. Our initial plan was to have the boss's stats as part of the overarching Stats class, but my fear is that this might violate the single responsibility principle since the boss's stats implementation might be something that the person working on boss fights might want to change. Thus, for now, having a separate Boss class might be the best way forward. If needed we can always refactor into a single class if we think that this is fit.

Another possibility might be to maybe have a facade design pattern so that the two classes have a single interface and can share the common methods? Something to think about.

**Comment by AVLTG** [comment]
You could perhaps create the "main" stats for both the player and the boss, and I can use your stats to create "temporary" stats for the player and the boss that I can change because we don't want to edit either the damage or the health of the player permanently unless they beat the boss, so I could take a temporary health value where boss fight runs unless the temp health is 0, and the temp health is set to the max health every time the boss fight is initialized? I think that would be the easiest for both of us.
